<script lang="ts" src="./CoverThumb.ts" />
<template>
	<div class="relative">
		<div v-if="prompt" class="absolute bottom-md w-full bg-black bg-opacity-70 px-md py-4xs">
			<p class="text-white text-base">Generated by:</p>
			<p class="text-white text-sm italic">"{{ prompt }}"</p>
		</div>
		<nuxt-img :provider="provider" :src="src" :alt="alt" class="aspect-1 w-full bg-blue-galaxy">
		</nuxt-img>
	</div>
</template>
