<script src="./Generator.ts" lang="ts"></script>
<template>
	<div class="w-full">
		<form class="flex mb-md" @submit.prevent="generateImage">
			<input
				v-model="prompt"
				type="text"
				class="rounded-l-sm w-full p-3xs text-base"
				placeholder="Example: Death Valley art"
			/>
			<button
				class="bg-yellow-energy-yellow text-base text-white rounded-r-sm px-lg py-2xs min-w-[30rem] hover:bg-yellow-brick-road"
			>
				Generate
			</button>
		</form>
		<OrganismStyleSelect
			:styles="styles"
			:active-index="activeStyleIndex"
			@select="activeStyleIndex = $event"
		/>
		<ClientOnly>
			<p
				v-if="
					!isAuthenticated && !authIsLoading && (generatedImages.length || isGenerating)
				"
				class="mt-md text-white text-base text-center"
			>
				You need to
				<button
					class="text-yellow-energy-yellow hover:text-yellow-brick-road"
					@click="login"
				>
					login
				</button>
				to save images and to generate in high resolution
			</p>
		</ClientOnly>
		<ClientOnly v-if="generatedImages.length || isGenerating">
			<div class="bg-blue-whale py-sm px-lg flex justify-center mt-md">
				<div v-if="isGenerating">
					<p class="text-white text-md text-center">Generating cover</p>
					<p class="text-white text-sm text-center">Wait a couple of minutes</p>
					<SvgLoader />
				</div>
				<div v-else class="aspect-1 w-full bg-blue-thoughts max-w-[90rem]">
					<div v-if="generatedImages.length" class="flex flex-wrap">
						<div
							v-for="(image, n) in generatedImages"
							:key="image"
							class="w-1/2 relative"
						>
							<button
								v-if="isAuthenticated"
								class="bg-white border border-blue-cornflower rounded-sm px-4xs text-base absolute top-4xs right-4xs z-10 hover:border-white hover:bg-blue-light-house hover:text-white"
							>
								Save Image
							</button>
							<nuxt-img
								provider=""
								:src="image"
								:alt="`AI generated album cover ${n} of ${generatedImages.length}`"
								class="aspect-1 w-full bg-blue-galaxy"
							>
							</nuxt-img>
						</div>
					</div>
				</div>
			</div>
		</ClientOnly>
		<div v-else>
			<div class="flex items-center flex-col mt-md">
				<div class="flex flex-col items-center">
					<SvgArrowUp class="text-yellow-energy-yellow w-[10rem] mb-sm" />
					<h2 class="text-white italic text-md font-light mb-md">
						1. Write what you want on your album cover <br />
						2. Select a style <br />
						3. click generate
					</h2>
					<div>
						<p
							v-for="text in [
								`All content generated by DeepAI's tools and APIs are free of copyright, <br/>you may use them for any legal purpose you wish including commercial use`,
							]"
							:key="text"
							class="text-blue-cornflower italic text-sm"
							v-html="'* ' + text"
						></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>
